spring:
  application:
    name: actuator-demo

logging:
  level:
    com.example.actuator_demo: debug

management:
# 활설화 설정.
  endpoint:
    health:
#      enabled: true
#      cache:
#        time-to-live: 1d #Duration 1d, 1ms, 1s
#      show-components: ALWAYS
      show-details: ALWAYS
    env:
      show-values: ALWAYS
# 노출 설정.
  endpoints:
    web:
#      cors:
#        allowed-origins: http://test.com, http://test2.com
#        allowed-methods: GET
      exposure:
        include: "*"  #모든 정보 노출. beans만 제외.
#        exclude:
#          - beans
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: FULL
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application Build and Run: -Dinfo.name=tester
info:
  my-app:
    any-value: something
    group-id: "@project.groupId@" # pom.xml-project-groupId
    artifact-id: "@project.groupId@"
  name: heopanman